### ISSUE TITLE
Error command -c e -delete

### ISSUE THREAD

**Issue by onimur** [cibuilds/github#8]
Hello, 
I appreciate the work with this repository, used in many projects.
Since today, the coma -c and -delete are not being recognized.

>> ==> Create a new release
>> / bin / bash: line 8: -c: command not found
>> Exited with code exit status 127

and

>> ==> Create a new release
>> / bin / bash: line 9: -delete: command not found
>> Exited with code exit status 127

After that, the pipeline enters a loop with the following commit messages:
untagged-94fed5bdc337a462ce35, the value of which varies.
I need to go to the project settings in the circleci and stop them manually.

I have this config.yml:

```yml
version: 2.1 # Use 2.1 to enable using orbs and other features.

jobs:
  publish-github-release:
    docker:
      - image: cibuilds/github:0.13

      - run:
          name: Publish Release on GitHub
          command: | 
            DATE=$(date +'%m-%d-%y')
            printf -v BODY "$(curl -s 'https://raw.githubusercontent.com/onimur/circleci-github-changelog-generator/master/docs/RELEASE_TEMPLATE.md')" "${CIRCLE_PROJECT_REPONAME}" "${DATE}" "${CIRCLE_TAG}" "${CIRCLE_BUILD_NUM}" "${CIRCLE_BUILD_URL}"
            ghr \
            -t ${GITHUB_TOKEN} \
            -u ${CIRCLE_PROJECT_USERNAME} \
            -r ${CIRCLE_PROJECT_REPONAME}  \
            -b "${BODY}" \ 
            -c ${CIRCLE_SHA1}  \
            -delete ${CIRCLE_TAG}

workflows:
  build_and_test:
    jobs: 
      - publish-github-release:
          context: main-context
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/ # for all tags       
```

Have any suggestion?

![Errors](https://user-images.githubusercontent.com/46748882/87607208-2fc41480-c6d3-11ea-8131-3742520d5dd0.JPG)
